export const DISPLAY = [
  {
    displayId: 1,
    displayNm: '가온전시실',
    images: [
      {
        imgId: 1,
        imgNm: 'display_image_1',
        sort: 1,
        imgPath: 'https://i.postimg.cc/GpfwJF6d/IMG-0414.jpg',
        fileFormat: 'jpg',
      },
      {
        imgId: 2,
        imgNm: 'display_image_2',
        sort: 1,
        imgPath: 'https://i.postimg.cc/GpfwJF6d/IMG-0414.jpg',
        fileFormat: 'jpg',
      },
      {
        imgId: 3,
        imgNm: 'display_image_3',
        sort: 2,
        imgPath: 'https://i.postimg.cc/GpfwJF6d/IMG-0414.jpg',
        fileFormat: 'png',
      },
      {
        imgId: 4,
        imgNm: 'display_image_4',
        sort: 2,
        imgPath: 'https://i.postimg.cc/GpfwJF6d/IMG-0414.jpg',
        fileFormat: 'jpg',
      },
      {
        imgId: 5,
        imgNm: 'display_image_5',
        sort: 3,
        imgPath: 'https://i.postimg.cc/GpfwJF6d/IMG-0414.jpg',
        fileFormat: 'png',
      },
      {
        imgId: 6,
        imgNm: 'display_image_6',
        sort: 3,
        imgPath: 'https://i.postimg.cc/GpfwJF6d/IMG-0414.jpg',
        fileFormat: 'jpg',
      },
      {
        imgId: 7,
        imgNm: 'display_image_7',
        sort: 4,
        imgPath: 'https://i.postimg.cc/GpfwJF6d/IMG-0414.jpg',
        fileFormat: 'jpeg',
      },
    ],
  },
  {
    displayId: 2,
    displayNm: '파이룸',
    images: [
      {
        imgId: 1,
        imgNm: 'display_image_1',
        sort: 1,
        imgPath: 'https://i.postimg.cc/GpfwJF6d/IMG-0414.jpg',
        fileFormat: 'jpg',
      },
      {
        imgId: 2,
        imgNm: 'display_image_2',
        sort: 2,
        imgPath: 'https://i.postimg.cc/GpfwJF6d/IMG-0414.jpg',
        fileFormat: 'png',
      },
      {
        imgId: 3,
        imgNm: 'display_image_3',
        sort: 3,
        imgPath: 'https://i.postimg.cc/GpfwJF6d/IMG-0414.jpg',
        fileFormat: 'jpg',
      },
      {
        imgId: 4,
        imgNm: 'display_image_4',
        sort: 4,
        imgPath: 'https://i.postimg.cc/GpfwJF6d/IMG-0414.jpg',
        fileFormat: 'jpeg',
      },
      {
        imgId: 5,
        imgNm: 'display_image_5',
        sort: 5,
        imgPath: 'https://i.postimg.cc/GpfwJF6d/IMG-0414.jpg',
        fileFormat: 'png',
      },
      {
        imgId: 6,
        imgNm: 'display_image_6',
        sort: 6,
        imgPath: 'https://i.postimg.cc/GpfwJF6d/IMG-0414.jpg',
        fileFormat: 'jpg',
      },
      {
        imgId: 7,
        imgNm: 'display_image_7',
        sort: 7,
        imgPath: 'https://i.postimg.cc/GpfwJF6d/IMG-0414.jpg',
        fileFormat: 'jpeg',
      },
    ],
  },
];
